apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xjiangazureci0602-gitops
  description: This is GitOps manifest for xjiangazureci0602   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=xjiangazureci0602
    backstage.io/kubernetes-id: xjiangazureci0602 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: xjiangorg/xjiangazureci0602-gitops
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: xjiangorg.xjiangazureci0602-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xjiangazureci0602
