apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: xjiangazureci0602
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xjiangazureci0602 
  name: xjiangazureci0602
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: xjiangazureci0602
    weight: 100 
