apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xjiangazureci0602
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xjiangazureci0602 
  name: xjiangazureci0602
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xjiangazureci0602 
